/* exported sampleStores */
// Alberta bakery data for WalkBread
const sampleStores = [
  {
    id: 'calgary-amandine-bakery',
    name: 'Amandine Bakery',
    address: {
      street: '2612 Centre Street NE',
      city: 'Calgary',
      state: 'AB',
      zip: 'T2E 2V2',
      coordinates: { lat: 51.0753623, lng: -114.0620612 },
    },
    contact: {
      phone: '+1 403-805-7300',
      website: 'https://www.amandinebakery.net/',
      email: '',
    },
    hours: {
      monday: '08:00 AM - 06:00 PM',
      tuesday: '08:00 AM - 06:00 PM',
      wednesday: '08:00 AM - 06:00 PM',
      thursday: '08:00 AM - 06:00 PM',
      friday: '08:00 AM - 06:00 PM',
      saturday: '08:00 AM - 05:00 PM',
      sunday: 'Closed',
    },
    pricing: '$$',
    rating: 4.6,
    reviewCount: 215,
    specialties: ['viennoiserie', 'artisan bread', 'entremets'],
    dietary: {
      glutenFree: false,
      vegan: false,
      organic: false,
    },
    offerings: {
      bread: true,
      pastries: true,
      coffee: true,
      sandwiches: true,
    },
    images: [
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop',
    ],
    description:
      'Family-run French bakery crafting laminated pastries, specialty cakes, and savoury lunch items with a Parisian flair.',
    languages: ['en', 'fr'],
    distance: Number.POSITIVE_INFINITY,
  },
  {
    id: 'calgary-pie-junkie-crowfoot',
    name: 'Pie Junkie Crowfoot',
    address: {
      street: '826 Crowfoot Crescent NW',
      city: 'Calgary',
      state: 'AB',
      zip: 'T3G 4S3',
      coordinates: { lat: 51.1270023, lng: -114.2066331 },
    },
    contact: {
      phone: '+1 403-241-3475',
      website: 'https://piejunkie.ca/',
      email: 'hello@piejunkie.ca',
    },
    hours: {
      monday: '10:00 AM - 07:00 PM',
      tuesday: '10:00 AM - 07:00 PM',
      wednesday: '10:00 AM - 07:00 PM',
      thursday: '10:00 AM - 07:00 PM',
      friday: '10:00 AM - 07:00 PM',
      saturday: '10:00 AM - 07:00 PM',
      sunday: '10:00 AM - 07:00 PM',
    },
    pricing: '$$',
    rating: 4.7,
    reviewCount: 540,
    specialties: ['butter crust pies', 'tourtière', 'take-home meals'],
    dietary: {
      glutenFree: true,
      vegan: false,
      organic: false,
    },
    offerings: {
      bread: false,
      pastries: true,
      coffee: false,
      sandwiches: false,
    },
    images: [
      'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&auto=format&fit=crop',
    ],
    description:
      'Signature sweet and savoury pies baked daily in small batches, featuring Alberta-sourced butter and seasonal produce.',
    languages: ['en'],
    distance: Number.POSITIVE_INFINITY,
  },
  {
    id: 'calgary-jelly-modern-doughnuts',
    name: 'Jelly Modern Doughnuts',
    address: {
      street: '1414 8 Street SW #100',
      city: 'Calgary',
      state: 'AB',
      zip: 'T2R 1J6',
      coordinates: { lat: 51.039903, lng: -114.081459 },
    },
    contact: {
      phone: '+1 403-453-2053',
      website: 'https://www.jellymoderndoughnuts.com/',
      email: '',
    },
    hours: {
      monday: '09:00 AM - 05:00 PM',
      tuesday: '09:00 AM - 05:00 PM',
      wednesday: '09:00 AM - 05:00 PM',
      thursday: '09:00 AM - 05:00 PM',
      friday: '09:00 AM - 05:00 PM',
      saturday: '09:00 AM - 05:00 PM',
      sunday: '09:00 AM - 05:00 PM',
    },
    pricing: '$$',
    rating: 4.5,
    reviewCount: 865,
    specialties: ['yeast doughnuts', 'maple bacon', 'artisan fillings'],
    dietary: {
      glutenFree: false,
      vegan: true,
      organic: false,
    },
    offerings: {
      bread: false,
      pastries: true,
      coffee: true,
      sandwiches: false,
    },
    images: [
      'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?w=800&auto=format&fit=crop',
    ],
    description:
      'Award-winning gourmet doughnut shop known for brioche dough, local ingredients, and rotating chef-inspired flavours.',
    languages: ['en'],
    distance: Number.POSITIVE_INFINITY,
  },
  {
    id: 'lethbridge-bootsma-bakery',
    name: 'Bootsma Bakery',
    address: {
      street: '1418 17 Street S',
      city: 'Lethbridge',
      state: 'AB',
      zip: 'T1K 1Y7',
      coordinates: { lat: 49.677932, lng: -112.8189739 },
    },
    contact: {
      phone: '+1 403-327-3311',
      website: 'https://www.facebook.com/BootsmaBakery/',
      email: '',
    },
    hours: {
      monday: 'Closed',
      tuesday: '08:00 AM - 05:00 PM',
      wednesday: '08:00 AM - 05:00 PM',
      thursday: '08:00 AM - 05:00 PM',
      friday: '08:00 AM - 05:00 PM',
      saturday: '08:00 AM - 04:00 PM',
      sunday: 'Closed',
    },
    pricing: '$',
    rating: 4.8,
    reviewCount: 190,
    specialties: ['Dutch breads', 'sausage rolls', 'butter tarts'],
    dietary: {
      glutenFree: false,
      vegan: false,
      organic: false,
    },
    offerings: {
      bread: true,
      pastries: true,
      coffee: false,
      sandwiches: false,
    },
    images: [
      'https://images.unsplash.com/photo-1572293880614-38c1d0a41c05?w=800&auto=format&fit=crop',
    ],
    description:
      'Local favourite for European-style loaves, buns, and sweets baked fresh each morning in the city’s south side.',
    languages: ['en', 'nl'],
    distance: Number.POSITIVE_INFINITY,
  },
  {
    id: 'lethbridge-crazy-cakes',
    name: 'Crazy Cakes',
    address: {
      street: '403 11 Street S',
      city: 'Lethbridge',
      state: 'AB',
      zip: 'T1J 2P5',
      coordinates: { lat: 49.6926082, lng: -112.8301954 },
    },
    contact: {
      phone: '+1 403-380-4443',
      website: 'https://crazycakes.ca/',
      email: 'orders@crazycakes.ca',
    },
    hours: {
      monday: 'Closed',
      tuesday: '10:00 AM - 05:00 PM',
      wednesday: '10:00 AM - 05:00 PM',
      thursday: '10:00 AM - 05:00 PM',
      friday: '10:00 AM - 05:00 PM',
      saturday: '10:00 AM - 04:00 PM',
      sunday: 'Closed',
    },
    pricing: '$$',
    rating: 4.7,
    reviewCount: 160,
    specialties: ['custom cakes', 'cupcakes', 'espresso'],
    dietary: {
      glutenFree: true,
      vegan: true,
      organic: false,
    },
    offerings: {
      bread: false,
      pastries: true,
      coffee: true,
      sandwiches: false,
    },
    images: [
      'https://images.unsplash.com/photo-1483695028939-5bb13f8648b0?w=800&auto=format&fit=crop',
    ],
    description:
      'Boutique cake studio whipping up imaginative celebration cakes, cupcakes, and coffee drinks with plenty of dietary-friendly options.',
    languages: ['en'],
    distance: Number.POSITIVE_INFINITY,
  },
];
